version: '3'

services:
  mongo:
    image: mongo
    container_name: order-payment-microservice-poc-mongo
#    restart: always
    ports:
      - 27017:27017
    volumes:
      - my-datavolume:/data/db

volumes:
  my-datavolume: